services:
  checkpointlibrary:
    image: node:18
    container_name: checkpointlibrary
    environment:
      - CONN_STR=mongodb+srv://user:pass@checkpointdb.x6bpf.mongodb.net/?retryWrites=true&w=majority&appName=checkpointdb
    volumes:
      - ./app:/usr/src/app
    working_dir: /usr/src/app
    command: 'npm install && npm start'
    depends_on:
      - mongodb
    ports:
      - "3000:3000"

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db